# Generated by Django 5.1.4 on 2025-01-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ensino',
            fields=[
                ('cod_ensino', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ensino', models.CharField(max_length=100)),
            ],
        ),
    ]
