# Generated by Django 5.1.4 on 2025-01-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ano',
            fields=[
                ('cod_ano', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('ano', models.CharField(max_length=4)),
            ],
        ),
    ]
