# Generated by Django 5.1.4 on 2025-01-15 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ensinos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('cod_etapa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('etapa', models.CharField(max_length=100)),
                ('ensino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='ensinos.ensino')),
            ],
        ),
    ]
