# Generated by Django 5.1.4 on 2025-01-16 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descritores', '0001_initial'),
        ('disciplinas', '0002_rename_eixo_disciplina_area_conhecimento_and_more'),
        ('programas', '0001_initial'),
        ('subprogramas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matriz',
            fields=[
                ('cod_matriz', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('matriz', models.CharField(max_length=200)),
                ('descritores', models.ManyToManyField(related_name='matrizes', to='descritores.descritor')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='disciplinas.disciplina')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='programas.programa')),
                ('subprograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='subprogramas.subprograma')),
            ],
        ),
    ]
