# Generated by Django 5.1.4 on 2025-01-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0001_initial'),
        ('matrizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriz',
            name='etapa',
            field=models.ForeignKey(default='01', on_delete=django.db.models.deletion.CASCADE, related_name='matrizes', to='etapas.etapa'),
            preserve_default=False,
        ),
    ]
