# Generated by Django 5.1.4 on 2025-01-17 17:35

import django.db.models.deletion
import django_quill.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demandas', '0002_item_data_elaborador_item_data_revisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElaboracaoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gabarito', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, null=True)),
                ('conteudo', django_quill.fields.QuillField(blank=True, null=True)),
                ('comando', django_quill.fields.QuillField(blank=True, null=True)),
                ('alternativa_a', django_quill.fields.QuillField(blank=True, null=True)),
                ('alternativa_b', django_quill.fields.QuillField(blank=True, null=True)),
                ('alternativa_c', django_quill.fields.QuillField(blank=True, null=True)),
                ('alternativa_d', django_quill.fields.QuillField(blank=True, null=True)),
                ('alternativa_e', django_quill.fields.QuillField(blank=True, null=True)),
                ('justificativa_a', django_quill.fields.QuillField(blank=True, null=True)),
                ('justificativa_b', django_quill.fields.QuillField(blank=True, null=True)),
                ('justificativa_c', django_quill.fields.QuillField(blank=True, null=True)),
                ('justificativa_d', django_quill.fields.QuillField(blank=True, null=True)),
                ('justificativa_e', django_quill.fields.QuillField(blank=True, null=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='elaboracao', to='demandas.item')),
            ],
        ),
    ]
