# Generated by Django 5.2.1 on 2025-05-16 03:26

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elaborar_itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elaboracaoitem',
            name='revisao_texto',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
