# Generated by Django 5.1.4 on 2025-01-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etapas', '0001_initial'),
        ('programas', '0001_initial'),
        ('subprogramas', '0002_subprograma_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='subprograma',
            name='etapas_avaliadas',
            field=models.ManyToManyField(related_name='subprogramas', to='etapas.etapa'),
        ),
        migrations.AlterField(
            model_name='subprograma',
            name='programa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='subprogramas', to='programas.programa'),
        ),
    ]
