# Generated by Django 5.1.4 on 2025-01-14 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('cod_grupo', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('nome_grupo', models.CharField(max_length=80)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
