# Generated by Django 5.2.1 on 2025-05-17 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=100)),
                ('etapa', models.CharField(max_length=100)),
                ('descritor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRevisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_designacao', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='revisao.item')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_designados', to='usuarios.usuario')),
            ],
        ),
    ]
