# Generated by Django 5.2.1 on 2025-05-17 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0003_item_consideracoes_revisor'),
        ('revisao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrevisor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demandas.item'),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
