# Generated by Django 5.1.4 on 2025-01-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PadraoItem',
            fields=[
                ('cod_padrao_item', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('padrao_item', models.CharField(max_length=100)),
            ],
        ),
    ]
