# Generated by Django 5.1.4 on 2025-01-17 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('descritores', '0001_initial'),
        ('disciplinas', '0002_rename_eixo_disciplina_area_conhecimento_and_more'),
        ('etapas', '0001_initial'),
        ('matrizes', '0002_matriz_etapa'),
        ('padrao_item', '0001_initial'),
        ('tipo_item', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('cod_demanda', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome_demanda', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True, max_length=700)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('cod_item', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('qtd_itens', models.PositiveIntegerField()),
                ('status_item', models.CharField(default='A Elaborar', max_length=20)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='demandas.demanda')),
                ('descritor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='descritores.descritor')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
                ('elaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elaborador', to='usuarios.usuario')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='etapas.etapa')),
                ('matriz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matrizes.matriz')),
                ('padrao_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='padrao_item.padraoitem')),
                ('revisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisor', to='usuarios.usuario')),
                ('tipo_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tipo_item.tipoitem')),
            ],
        ),
    ]
