# Generated by Django 5.1.4 on 2025-01-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='data_elaborador',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='data_revisor',
            field=models.DateField(blank=True, null=True),
        ),
    ]
