# Generated by Django 5.2.1 on 2025-05-17 00:26

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandas', '0002_item_data_elaborador_item_data_revisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='consideracoes_revisor',
            field=django_quill.fields.QuillField(blank=True, null=True),
        ),
    ]
