# Generated by Django 5.1.4 on 2025-01-15 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0002_rename_eixo_disciplina_area_conhecimento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Descritor',
            fields=[
                ('cod_descritor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descritor', models.TextField(max_length=350)),
                ('cod_eixo', models.CharField(max_length=10)),
                ('eixo', models.CharField(max_length=100)),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descritores', to='disciplinas.disciplina')),
            ],
        ),
    ]
