# Generated by Django 5.1.4 on 2025-01-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplina',
            old_name='eixo',
            new_name='area_conhecimento',
        ),
        migrations.RenameField(
            model_name='disciplina',
            old_name='cod_eixo',
            new_name='sigla',
        ),
    ]
